language: node_js

node_js:
  - 4
  - 5
  - 6

os:
  - linux

matrix:
  fast_finish: true

sudo: false

cache: yarn

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
  mariadb: "10.0"

before_install:
  - export CXX=g++-4.8; export CC=gcc-4.8;

before_script:
    - mysql -e "create database db_migrate_test;"
    - createdb db_migrate_test
    - cp test/db.config.ci test/db.config.json
